name: Bug Report
description: Report a bug, error, or unintended behavior.
title: "[Bug] "
labels: ["T: Bugfix", "Issue: Needs Replicating", "S: Untriaged"]

body:
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: Explain the issue and what you expected to happen.
      placeholder: "E.g., The game crashes when doing ..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug.
      placeholder: |
        1. Do this
        2. Do that
        3. Issue occurs
    validations:
      required: true

  - type: dropdown
    id: mod_version
    attributes:
      label: Mod Version
      description: Select the version of the mod you are using.
      options:
        - Mod Name
        - Mod Name2
        - Mod Name3
        - Mod Name4
      default: 0   
    validations:
      required: true

  - type: input
    id: build_number
    attributes:
      label: Build Number
      description: Specific build number of the mod.
      placeholder: "release-1.1.0"

  - type: textarea
    id: logs
    attributes:
      label: Logs & Screenshots
      description: Attach screenshots or log files to help debug.
      placeholder: "Required!"
    validations:
      required: true

  - type: checkboxes
    id: unique_check
    attributes:
      label: I have checked existing issues...
      options:
        - label: "...and this bug was not reported before."
          required: true

