name: Feature Request
description: File a feature request.
labels: ["T: New feature", "S: Untriaged"]

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What theme do you want the mod to be based on?
      placeholder: Tell us what you want!
      value: |
        I want the mod to be based on Art Deco.
    validations:
      required: true

  - type: textarea
    id: inspiration
    attributes:
      label: Images / inspiration & related resources
      description: |
        Tip: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: I've checked the feature requests...
      options:
        - label: |
            ...and this theme was not requested before.
          required: true
