name: Feature Request
description: Suggest a new theme or feature for the mod.
title: "[Feature] "
labels: ["T: New feature", "S: Untriaged"]

body:
  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Provide a short description of the feature or theme you want.
      placeholder: "E.g., Add Art Deco theme"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Detailed Explanation
      description: Explain the feature in more detail. Why is it useful or interesting?
      placeholder: "Describe how this feature or theme would work..."
    validations:
      required: true

  - type: textarea
    id: resources
    attributes:
      label: Images / Inspiration & Related Resources
      description: Attach images, references, or links to help illustrate your idea.
      placeholder: "Optional"
    validations:
      required: false

  - type: checkboxes
    id: unique_check
    attributes:
      label: I have checked existing feature requests...
      options:
        - label: "...and this feature or theme was not requested before."
          required: true

